name: Lint docs
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Remove ignored files
          run: rm -rf lib/epuber/third_party

        - name: Run link check
          uses: gaurav-nelson/github-action-markdown-link-check@v1
          with:
            use-quiet-mode: 'no'
            use-verbose-mode: 'yes'
            config-file: '.github/config/markdown.links.config.json'
